### ISSUE TITLE
Additional bibtex keys

### ISSUE THREAD

**Issue by cbows** [alejandrogallo/papis#10]
When I export my library to bibtex some entries I specified in the `info.yaml` don't show up. I figured out that only bibtex keys listed in `bibtex.py` are exported.

```python
bibtex_keys = [
  "address",
  "annote",
  "author",
#...
]
```
Is it possible to customize this list in a permanent way?

**Comment by alejandrogallo** [comment]
I think it does make sense to customize it, I accept the request

**Comment by alejandrogallo** [comment]
Now you can add extra custom keys and document types for bibtex
exporting by setting the `extra-bibtex-keys` and `extra-bibtex-types`
with comma separated values, i.e., in the configuration file
```INI
[settings]
extra-bibtex-keys = address , annote , tags , file
extra-bibtex-types = song , review , phdthesis , wikipedia
```

**Comment by cbows** [comment]
Thank you very much.
