### ISSUE TITLE
Allow `ref` preferences to be set in config

### ISSUE THREAD

**Issue by michaelplews** [alejandrogallo/papis#16]
Some of the larger bibliography programs allow the style of the `ref` flag to be set in Preferences. The `ref` flag is used in referencing entries from bibtex files, and would be useful to remember off hand. Personally, I use the style AuthorYear e.g. `Plews2019`. It may be useful to allow users to add a preferred format which is used if the information is available when using the `--from-doi` flag (or similar).

An Example:
```
[settings]
ref-format = {doc[author]}{doc[year]}
```
Right now it defaults to the doi, which is good fallback behaviour.

I have a branch I was going to PR where I added a `--ref` flag (310e096), but this might be worth adding. I'm happy to work on this, I just can't figure out where/how you pull information from the config file, and how I would translate it into `papis add`.

**Comment by alejandrogallo** [comment]
Hi Michael. It is a fair and useful point that some people would like to customize.
I also think like you that it is better to define a configuration setting ``ref-format`` in line with the other
settings than define a flag in ``add``. The command ``add`` is now quite ``info.yaml`` file agnostic (with the exception of ``--author`` and ``--title``, which were added for real convenience).

I was thinking about whether implementing the ``ref-format`` in the ``add`` command or as you say in the data
retrievers like ``doi``. I think it makes more sense to put it in the data retrievers not to clutter
the ``add`` code even more (which by the way should be simplified a little bit, I have an uneasy feeling when I see that it is 500 loc...) 

I recently added the ``marks`` functionality to papis, 
([doc](http://papis.readthedocs.io/en/latest/configuration.html#config-settings-mark-header-format))
that you can take as example. 
The first thing you should have to do is registering the option ``ref-format``, which
is somehow loosely documented in the ``HACKING.md`` file:

Adding options
--------------

* Add a default value in `config.py`, along with a comment that describes the
  option.

The setting is now accessible with `papis.config.get('myoption')`
or through the cli interface `papis config myoption`.

And then you have to change the definition of ``ref`` when retrieving data from ``doi``,
which is done in the function: ``papis.crossref.doi_to_data``, specifically in line ``337`` of the
file ``crossref.py``. To know how to compile the string ``papis.config.get('ref-format')``
you can take a look at the lines:

```
                            opener = papis.utils.format_doc(
                                papis.config.get("mark-opener-format"),
                                mark, key=papis.config.get("mark-format-name")
                            )
```
found in the last version of the file ``open.py`` where the ``mark-opener-format`` is compiled
using the ``papis.utils.format_doc`` function.

Ask away if you have ANY questions or inquiries, and thank you soooo much
for this feature enhancement !

**Comment by alejandrogallo** [comment]
Hi Michael, how is it going? If you have any questions just feel free to ask :)

**Comment by michaelplews** [comment]
Thanks Alejandro. I'm actively working on this and will ask if/when I get stuck

**Comment by michaelplews** [comment]
I am stuck. In `crossref.py`, where I define `res["ref"]`, the following does not work:

```
res["ref"] = papis.utils.format_doc(papis.config.get("ref-format"),res, key=papis.config.get("ref-format")) 
```

it fails with:

```
ERROR:crossref:Couldn't resolve DOI '10.1039/C7TA04521B' through CrossRef: 'doc'
```

config
```
[settings]
ref-format = {doc[issue]}
```

using `res` instead of `doc` (`crossref.py`) is necessary because we haven't actually made the doc yet. However I'm not sure res behaves the same way. I think my issue is somehow confusing dicts with tuples.

Relevant commit: https://github.com/michaelplews/papis/commit/67ca46cc4cca47dfdba6b754451263e8a711b345

**Comment by alejandrogallo** [comment]
Hi, sorry for the delay, I think it is kind of my fault and due to the fast development pace.
So, papis is lying to you, the error is not a DOI resolvant but the exception catching in the crossref
part.
So the problem is that you are using a version of `papis.utils.format_doc` function that is too old,
you probably checked out the signature from the master branch and you assumed that
I'm not impolite and broke backwards compatibility for the signature, bad news is that
I am not very polite  :1st_place_medal: 
So the exception caching failing is in the ``doi_to_data`` function
```python
def doi_to_data(doi):
    """Search through crossref and get a dictionary containing the data

    :param doi: Doi identificator
    :type  doi: str
    :returns: Dictionary containing the data

    """
    global logger
    doi = get_clean_doi(doi)
    try:
        data = get_cross_ref(doi)
    except Exception as e:
        logger.error(
            "Couldn't resolve DOI '" + doi + "' through CrossRef: " + str(e) + "\n"
        )
        raise e
        return dict()
    else:
        return data
```
and I'm catching any kind of exception and saying that it's because I can't resolve the doi, which... well
in this case drove you nuts, sorry. If you actually raise the exceptioin `e` as I did in this snippet
you see
```
TypeError: format_doc() got an unexpected keyword argument 'key'
```
which is the error I was talking about, so your code was sound, you just were using a too outdated version of the `format_doc` function.

**Comment by michaelplews** [comment]
The version I am using seems to have the most updated form of `format_doc`:

```python
#utils.py

def format_doc(python_format, document, key=""):                                                                                                    
    """Construct a string using a pythonic format string and a document.                                                                            
                                                                                                                                                       
    :param python_format: Python-like format string.                                                                                                
        (`see <                                                                                                                                     
            https://docs.python.org/2/library/string.html#format-string-syntax                                                                      
        >`_)                                                                                                                                        
    :type  python_format: str                                                                                                                       
    :param document: Papis document                                                                                                                 
    :type  document: papis.document.Document                                                                                                        
    :returns: Formated string                                                                                                                       
    :rtype: str                                                                                                                                     
    """                                                                                                                                             
    doc = key or papis.config.get("format-doc-name")                                                                                                
    return python_format.format(**{doc: document})  
```

Is there an updated version you are referring to?
