### ISSUE TITLE
Import bib (zotero) fails if field is missing

### ISSUE THREAD

**Issue by nico202** [alejandrogallo/papis#17]
https://github.com/alejandrogallo/papis/blob/1f88cdc3bbb6cfdae7de72d3c8646fbb9ddacea3/examples/scripts/papis-zotero#L50

I'd do something like:
```
    print('INFO: Processing  |   ref: %s' % entry.get('ref',''))
    print('                  |Author: %s' % entry.get('author','Unknown'))
    print('                  | Title: %s' % entry.get('title','Untitled'))
```

**Comment by nico202** [comment]
Or warn or ask for fail/continue, something more defined

**Comment by alejandrogallo** [comment]
Agreed, this looks better, I also prompted the user for information!
Thanks very much for the reporting!
