### ISSUE TITLE
Import bib (zotero) fails finding file

### ISSUE THREAD

**Issue by nico202** [alejandrogallo/papis#18]
https://github.com/alejandrogallo/papis/blob/1f88cdc3bbb6cfdae7de72d3c8646fbb9ddacea3/examples/scripts/papis-zotero#L56

why the ":" split? for entries exported by zotero 5 at least, the file list separator is ";".

Also, you are taking the second ([1]) element, while on my export, pdf is always the first, followed (eventally) by an html. Maybe we should split on the separator (";" for me) and then iterate finding pdfs in file extension/mime?

**Comment by alejandrogallo** [comment]
Hello Nico, thank you very much for your enquiry.
I know that is not general, so we did this basing ourselves on a zotero sample. In that sample the format
was
```
DOCUMENT ID : DOCUMENT PATH : MORE INFORMATION
```
It is unfortunate that to my knowledge this format does not appear to be conserved depending on
``zotero`` or ``mendeley`` versions. That is the reason why the ``zotero`` script is an "example", that
every user can modify to their needs. I failed to see a general way to addressing this problem, although a work colleague is working on a script to decode the sql file and import directly from the sql file.

If you have a general solution to the problem, I am all ears.

**Comment by nico202** [comment]
I hope see a future for this package, since even if I like zotero, it's getting boring for me to cope with it (not available on my mobile, old packages on some distro, and so on). Sorry if I might have seemed rude, I'd just would like to help on it.
I also thought the output format was consistent between zotero versions. Also I don't know if it's in the standard, since I cannot find it here [1] (but I might be missing it)

Collecting "user feedback" (i.e., export formats) and managing all the options would be kind of nice btw.
I have a 500 item zotero library, so I might help in the sqlite parsing

[1] http://www.bibtex.org/

**Comment by alejandrogallo** [comment]
Hi Nico, you did not seem rude, don't worry at all! I appreciate very much your time.
It is a coincidence because I think the sqlite parsing script will be done by tonight, since my colleague
seems very eager to finishing it now and move on with his life. So I will be uploading it tonight,
it ill not use the ``papis-zotero`` script and it will correctly handle ``tags``, which I find zotero users
value very much.

I'll keep you updated here!

**Comment by nico202** [comment]
Nice, I'll wait and I'll try it out tomorrow then :)

**Comment by alejandrogallo** [comment]
So! It is done, it worked well for him, let's see if it works out for you too!
I would be very interested to figure out if it did ;)

http://papis.readthedocs.io/en/latest/importing.html#importing-from-zotero-sqlite-file

**Comment by nico202** [comment]
I replied by email but for some reason it's not appearing here.

I think we are on different versions, since the database field where named a bit differently.
Here's my "version" table:
```
"delete"	"54"
"translators"	"1510176069000"
"styles"	"1510176069000"
"system"	"32"
"compatibility"	"5"
"userdata"	"98"
"triggers"	"18"
"repository"	"1511258083"
"lastcheck"	"1511258084"
```
Reported version is: 5.0.25

The following diff works for me, I think we can select different query based on the db version
```
❯diff a b                                                                                                                                                                 ~/.config/papis/scripts
diff a/papis-zotero-sql b/papis-zotero-sql
80,81c80,81
<       creatorData.firstName,
<       creatorData.lastName
---
>       creators.firstName,
>       creators.lastName
85d84
<       creatorData,
90,91c89
<       creators.creatorID = itemCreators.creatorID AND
<       creatorData.creatorDataID = creators.creatorDataID
---
>       creators.creatorID = itemCreators.creatorID
126c124
<       itemAttachments.mimeType
---
>       itemAttachments.contentType
131,132c129,130
<       itemAttachments.sourceItemID = {itemID} AND
<       itemAttachments.mimeType IN {mimeTypes} AND
---
>       itemAttachments.parentItemID = {itemID} AND
>       itemAttachments.contentType IN {mimeTypes} AND
```

**Comment by nico202** [comment]
Zotero db compatibility check is done here:

https://github.com/zotero/zotero/blob/04a730da7fd32381535180c0ad105770ab919b43/chrome/content/zotero/xpcom/schema.js#L26-

**Comment by alejandrogallo** [comment]
I see, it is quite annoying that I do not know of a general tool to export zotero, but did you make
it to export it with your modifications?

**Comment by nico202** [comment]
Yes!

```papis  list | wc -l 
425
```

I think that having like:
```
sqlite_queries = {87:{"count":"SQL QUERY 1"},98:{"count":"SQL QUERY 2"}}

db_version = function_to_query_the_version_from_table()

query_version = max([ v for v in list(sqlite_queries .keys()) if v < db_version ])

if sqlite_queries.get(query_version, Null) != Null:
    # Do everything using sqlite_queries[query_version] - queries
else:
    # Error, ask the user to report their zotero version, printing the "version" table
```

**Comment by alejandrogallo** [comment]
Wonderful, we will take a look at this, however I will close this issue for the time being and
refer people to this link for the moment.
