### ISSUE TITLE
Scihub downloader failing

### ISSUE THREAD

**Issue by nico202** [alejandrogallo/papis#19]
https://github.com/alejandrogallo/papis/blob/1f88cdc3bbb6cfdae7de72d3c8646fbb9ddacea3/examples/scripts/papis-scihub#L29

Sci-hub.io seems down, while sci-hub.cc is ok. Maybe we can have a list of valid url, check for the first being alive, and use it.

```
❯curl sci-hub.io
curl: (6) Could not resolve host: sci-hub.io                                                                                                                                                      
❯curl sci-hub.cc
<index.html here>
```

**Comment by alejandrogallo** [comment]
Hello again! Yep, that's is right, and the domain name checking should have been done a long time ago.
So now the script checks which one works and then uses the working domain.

Thank you again!!
