### ISSUE TITLE
Crash when giving an empty string to papis rename

### ISSUE THREAD

**Issue by mftrhu** [alejandrogallo/papis#2]
Papis crashes when simply pressing enter at the `papis rename` prompt as it tries to perform a `mv folder/ folder/`, likely because of `default=document.get_main_folder_name()`. It should check for equality (or empty/invalid string) and quietly exit instead.

```
Enter new folder name:
> (paper_name):
[...]
Message: 'Path /home/mftrhu/Documents/papers/paper_name already exists!'
Arguments: ()
mv: cannot move '/home/mftrhu/Documents/papers/paper_name' to a subdirectory of itself, '/home/mftrhu/Documents/papers/paper_name/paper_name'
```

**Comment by alejandrogallo** [comment]
Wonderful! Good catch! Just fixed it. Thank you very much, again!
