### ISSUE TITLE
pdf import: rename file in a meaningful way

### ISSUE THREAD

**Issue by nico202** [alejandrogallo/papis#22]
When sharing all the papers, with zotero I did "find zotero_dir -iname "*.pdf" -exec cp {} output_dir \;".
Using ZotFile, the files where named after the paper year - author - title.

Now with papers downloaded from scihub, for example, I have a lot of "output.pdf". This is ugly also if using the "history" function of pdf viewers and so on, since it's difficult to remind which paper was it (on emacs interleave, notes are named like the source pdf, so having almost-unique name is a must).

I'd suggest to name them with doc[ref] (especially if it will be possible to customize the ref format) upon import and then don't touch them anymore

**Comment by alejandrogallo** [comment]
Hi! Yes that's true, in the add command there's a flag to name the folder `--name`, together with a configuration setting `add-name` but not for the files since in principle papis deals with files as second class citizens somehow, but the reasons  you give I think many people will have the same problem. So I think the behavior should be adding a flag and a setting for naming newly added files with a given papis format, and In the case that more than one file is to be added then a number can be appended at the end of the file name.

**Comment by michaelplews** [comment]
@alejandrogallo @nico202 I can take this one if you like. Looks very similar to PR (#32) except for checking if the file already exists and adding an incremental to the end if it does (this is also something I should check for with #32 but forgot to implement).

**Comment by alejandrogallo** [comment]
Hi Michael, thanks, I was taking a look at it parallely but I did not get to it yet.
If you'd like to do it that's great!. There is an additional thing that one ought to check and this is
that the full path of the filename does not exceed 255 characters for portability.
Some programs (specially pdf viewers and so, not to speak of weird OS's)
for some reason want a full path that does not exceed 255 characters.

You'll probably need too the function ``papis.utils.clean_document_name``.

Also I wanted to say, that you can rearrange the ``add`` code too, I think it is a little too bulky
and cluttered, but you can tell me as an external contributor if the variable names make sense etc...
Feel free to simplify it. It got very long sadly.

**Comment by nico202** [comment]
A resource I found useful about naming files is [this](http://beets.io/blog/paths.html) beets blog post.
(beets is a very powerful music organizer + more, and it's written in python, we might find useful info there)

**Comment by michaelplews** [comment]
Mark this as closed?
