### ISSUE TITLE
Parsing of BibTeX breaks with nested curly brackets

### ISSUE THREAD

**Issue by mftrhu** [alejandrogallo/papis#4]
Apparently BibTeX allows for nested curly brackets, seemingly to hint at names that shouldn't be decomposed or titles made into lowercase (see [here](https://tex.stackexchange.com/a/109070)), and Zotero will happily export BibTeX files containing them.

A minimal example file showcasing the problem, `test.bib`:
```
@article{haddaway_1993,
    title = {What is love? {Baby} don't hurt me},
    author = {Haddaway},
    month = may,
    year = {1993},
}
```

Running `papis add --from-bibtex test.bib --no-document` will thus result in a broken title. Further, it looks like the parsing somehow stops when encountering `month`, as if the positions of `year` and `month` are swapped `year` will appear in the output file.

The resulting `info.yaml` file:
```
author: Haddaway
files:
- info.yaml
ref: haddaway_1993
title: What is love? {Baby
type: article
```

**Comment by alejandrogallo** [comment]
Again a very good catch. It was working fine for most cases but having to support also non-bracketed values and brackets within brackets is for now reason enough to let a very well developed library handle it. So I have fixed the issue by incorporating ``bibtexparser``

 https://github.com/sciunto-org/python-bibtexparser

into papis' dependencies. It works very well and your example and the papis unittesting is passing.
Therefore I consider this issue closed.

One point is that thanks to the adoption of this library now we can convert a library file ( a file with
many bibtex entries) into a list of dictionaries. So we are close to being able to do the zotero conversion script.
