### ISSUE TITLE
tk dependency not declared

### ISSUE THREAD

**Issue by nico202** [alejandrogallo/papis#44]
https://github.com/alejandrogallo/papis/blob/3293d18de1a751bb1033e3899b923012adf56cce/papis/gui/tk/__init__.py#L4

Tk is neither optional nor required in setup.py
(it is required to have tests passing)

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Hi,

that's right, the problem I have with tkinter is that you can't really
declare it, right? It is not in the pypi.

So I assume you're encountering these issues building the installer for
NiX, so `tkinter` in my current understanding one should install in their
own distribution/machine, for instance

```
sudo apt-get install python3-tk
```

so I thought about just catching the import of tk,
and tell the user that to use the tk gui she has to install tkinter
in her own machine.

This is already done for the dmenu picker for instance
in `papis/gui/dmenu.py`

what do you think?

**Comment by nico202** [comment]
Oh, I'm not expert about pypi, I just thought that it would be possible to declare it.
I have no problems in adding it to nix, it just seemed to me like an hidden dependency, since it's not stated anywhere (readme, setup.py). I don't know how it done usually.

Oh, I found this comment right now on nix:

 Tkinter/tkinter is part of the Python standard library.
 The Python interpreters in Nixpkgs come without tkinter by default.
 To make the module available, we make it available as any other
 Python package.

If it's "standard library", no problem, sorry

**Comment by alejandrogallo** [comment]
Yes I also thought so until I encountered a OpenSuse distribution
where python3 does not come with either tkinter or curses...
But that's ok, thanks for addressing it anyways!
