### ISSUE TITLE
Add zotero conversion

### ISSUE THREAD

**Issue by alejandrogallo** [alejandrogallo/papis#5]
Does someone has a bibtex dump that I could use to develop it?

**Comment by mftrhu** [comment]
[Here you go](https://gist.github.com/mftrhu/d46fccf92273c716c4b30aa4bd3b92fa), a couple of papers from my library. Exported with Zotero 4.0.29.22, BibTeX, files included - not in the gist as directories are not supported, but the layout is a simple `./files/XXX/` and the reference(s) included in the `.bib` file like this:

```bibtex
file = {Full Text PDF:files/511/Hardell - 2017 - World Health Organization, radiofrequency radiatio.pdf:application/pdf;Snapshot:files/512/ijo.2017.html:text/html}
```

I'm not too sure of how Zotero will export filenames containing `:` or `;`, but it might just rename them by itself internally (almost certainly doing this with snapshots).

**Comment by alejandrogallo** [comment]
Wonderful! Thanks so much for this. So now I've implemented a very simple script to convert zotero to papis. 

It is in the repository's ``scripts`` folders, and it is called ``papis-zotero``. You can use it exactly like
the ``add`` command but with your bib file as the first argument.

You can use it as a stand alone script, i.e. ``./scripts/papis-zotero`` or move it to your
``$XDG_CONFIG_HOME/papis/scripts`` folder and then you will be able to see it in

```
papis -h
```

and use it like so:
```
papis zotero path/to/you/bibfile <add flags>
```

for instance if you want to get papis ask for confirmation before adding every paper and store the papers in the ``zotero`` subfolder of your library simply do like this

```
papis zotero path/to/bib --confirm -d zotero
```

If you've got a chance to test it and tell us your experience I'd be so thankful. If it works for you
I'll add this to the documentation, it is a fresh script but it should get the job done.

btw: I'll put you in the contributors list  if that's ok with you.

**Comment by mftrhu** [comment]
Just pulled and tried `papis-zotero` (I don't know whether it should work as `papis zotero`, I ran `make install` again afterwards but, even after uninstalling/re-installing, it doesn't appear on `papis -h` on my machine).

The import seems to be working fine, and all the fields seem to be present. A couple of problems though:

- nested brackets are preserved when importing, like this:

      title: A qualitative systematic review of factors influencing parents' vaccination
        decision-making in the {United} {Kingdom}

    I don't know whether this is intentional, as it could help when exporting back to BibTeX, but I'd shunt the original value to a new `title-raw` field and just strip them otherwise.

- when invoked as `./papis-zotero "~/Downloads/Exported Items/Exported Items.bib"`, `papis` __does__ detect the presence of a title field correctly, but can't find the file.

      INFO: File field detected (files/511/Hardell - 2017 - World Health Organization, radiofrequency radiatio.pdf)
      WARNING: Path (files/511/Hardell - 2017 - World Health Organization, radiofrequency radiatio.pdf) not found! Ignoring it

    The file is present.

      % l Exported\ Items/files/511
      total 568K
      568K 'Hardell - 2017 - World Health Organization, radiofrequency radiatio.pdf'

    This is because of `os.path.exists(pdf_file)`, where `pdf_file` is taken straight from the `file` field and thus the path likely considered relative to the point of invocation. The following addition fixes this.

        pdf_file = entry.get('file').split(':')[1]
      + pdf_file = os.path.join(os.path.dirname(bib_file), pdf_file)
        print('\tINFO: File field detected (%s)' % pdf_file)

The script otherwise works fine, albeit creating nested folders (`tmp_#####`) when invoked more than once on the same bib file.

---

> btw: I'll put you in the contributors list if that's ok with you.

I feel like I have yet to contribute anything meaningful but it's fine.

**Comment by alejandrogallo** [comment]
Thank you for the fix, it makes sense ( see, you contributed a fix right now, just without a pull request ).
I just fixed it.

About the brackets, yes, it is a 'feature' of the bibtex parser, I think for now I shall leave like this, although I'll put some thought into it.

I'm sorry maybe I did not explain well the ``papis-zotero``. So I copied the idea of ``git``, that if you
write a script named ``papis-whatever`` and you put it in your path or in ``$XDG_CONFIG_HOME/papis/scripts`` then you can run
```
papis whatever
```
so I was meaning this. This is probably poorly documented here

http://papis.readthedocs.io/en/latest/scripting.html

About the tmp files yes, we still have to implement a way of effectively detect when a document
has been already added in the past or not.

Thanks again for your help, thanks to you we've got a zotero converter in place!!
