### ISSUE TITLE
Possibly pulling BibTeX information from PubMed via HubMed

### ISSUE THREAD

**Issue by mftrhu** [alejandrogallo/papis#7]
Even if there is already an API available for PubMed via the Entrez retrieval system its output is in RIS format, as I already wrote briefly about on Reddit. But luckily it looks like there's a 3rd party interface available, [HubMed](http://www.hubmed.org/) ([Wikipedia page](https://en.wikipedia.org/wiki/HubMed), [help page](http://www.hubmed.org/help.htm)), which allows for search _and_ download of bibliographic data in BibTeX format - it looks like it's meant to be used interactively, and I couldn't find much in the way of description/help/ToS, but the data can be accessed directly.

As papis already uses a BibTeX library downloading and adding this information for any PMID should be about as easy as for a DOI.

[Example](http://pubmed.macropus.org/articles/?format=text%2Fbibtex&id=16006400):

```
curl "http://pubmed.macropus.org/articles/?format=text%2Fbibtex&id=16006400"
```

Resulting in

```
@Article{Lester2004,
author="Lester, David",
title="The suicide rate in the concentration camps was extraordinarily high: a comment on Bronisch and Lester.",
journal="Archives of suicide research : official journal of the International Academy for Suicide Research",
year="2004",
volume="8",
number="2",
pages="199--201",
abstract="Previous reports, based on limited reports from inmates who survived the Nazi concentration camps, have claimed that suicide was rare in the concentration camps. Using slightly more detailed, but nonetheless still limited, data from survivors of the camps, it is estimated that the suicide rates in the camp were most likely 25,000 per 100,000 per year or higher and, therefore, enormous!",
issn="1381-1118",
doi="10.1080/13811110490271425",
url="http://www.ncbi.nlm.nih.gov/pubmed/16006400",
language="eng"
}
```

**Comment by mftrhu** [comment]
I went ahead and wrote a python snippet to do exactly this. It's not thoroughly tested if at all - but it should work, and does so On My Machine™ - and as I mostly use it for personal projects I'm still not familiar with GitHub's collaboration model so I'll leave it here.

```python
self.parser.add_argument(
    "--from-pmid",
    help="PMID to try to get information from",
    default=None,
    action="store"
)
```

```python
if self.args.from_pmid:
    self.logger.debug("I'll try using PMID %s via HubMed" % self.args.from_pmid)
    hubmed_url = "http://pubmed.macropus.org/articles/?format=text%%2Fbibtex&id=%s" % self.args.from_pmid
    bibtex_data = papis.downloaders.utils.get_downloader(
        hubmed_url,
        'get'
    ).getDocumentData().decode("utf-8")
    bibtex_data = papis.bibtex.bibtex_to_dict(bibtex_data)
    if len(bibtex_data):
        data.update(bibtex_data[0])
    else:
        self.logger.error("PMID %s not found or invalid" % self.args.from_pmid)
```

**Comment by alejandrogallo** [comment]
Hi! Thanks, I think it is a very good thing to have around, specially if you use this.
I have no complaint with your code, very clean and following the same conventions as with the rest
of the code, wonderful!

**Comment by mftrhu** [comment]
> - I was thinking also to add doi compatibility for your code, in principle you can complement the
    data from hubmed with the in place doi parser in papis, so
> ```python
> if len(bibtex_data):
>    data.update(bibtex_data[0])
>    if 'doi' in data.keys() and not self.args.from_doi:
>         self.args.from_doi = data['doi']
> ```
> something like this, but I can add it at some point after it. Thanks again!

If I understood you correctly you want to try pulling data from [HP]ubMed *before* getting to the DOI branch so we can leverage that to possibly download the full-text when available? Not a problem, I forked and will push/create a PR in a minute.

**Comment by alejandrogallo** [comment]
```__        _____  _   _ ____  _____ ____  _____ _   _ _     _ _ 
\ \      / / _ \| \ | |  _ \| ____|  _ \|  ___| | | | |   | | |
 \ \ /\ / / | | |  \| | | | |  _| | |_) | |_  | | | | |   | | |
  \ V  V /| |_| | |\  | |_| | |___|  _ <|  _| | |_| | |___|_|_|
   \_/\_/  \___/|_| \_|____/|_____|_| \_\_|    \___/|_____(_|_)
```                                                               
Thank you very much!

**Comment by hubgit** [comment]
For reference, in case the service at http://pubmed.macropus.org/articles/ ever goes away, it's fetching the XML record from NCBI's eFetch service[1], converting it to MODS using `med2xml` then converting it to BibTeX using `xml2bib` (both of which are part of [bibutils](http://bibutils.refbase.org/)).


[1] e.g. https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=11748933&retmode=xml

**Comment by alejandrogallo** [comment]
Hi @hubgit , thank you very much.
